### ISSUE TITLE
unable to get a result for draw.lines()

### ISSUE THREAD

**Issue by tcreuro** [ajfisher/randomwalks#3]
Hi @ajfisher,

Thank you for creating a fun program.

It took me a while to get some results and thought others maybe having similar issues.

Looking through what is available, lines is not listed.

CircleChord
CircleField
ChaikinPoly
ChaikinPolyDots
Concentrics
Connected
Curves
DeformedQuads
FlowField
FuzzyCurve
Grasses
Lamps
LineSubdivision
MaskedDots
MultiBands
Palette
Path
Rings
Scratch
SimplexBands
Split
Topography
Trees 

Should readme.md be updated? I can create a pull request if you like.

I would also like to know if I am using the correct versions of node (nvm installed) and cairo (brew installed) based on randomwalks development?

If you could shed some light on whether brew uninstall cairo and it's components and add cairo using MacPorts.

Then update to a later version of node?

System used for this build:

macOS 10.13.6
Xcode 10.1
Build version 10B61

Working versions for me.

`nvm current`
>v8.13.0

`brew info cairo`
>cairo: stable 1.16.0(bottled)

// Install Randomwalks

`npm install`

npm warnings...

`npm run dev`

// Using Chrome > More Tools > Developer Tools

draw.Palette()
works

//Using Firefox > Web Developer > Web Console

draw.Palette()
works

**Comment by tcreuro** [comment]
git pull
Already up to date.


Thank you for a brilliant bit of code!

**Comment by ajfisher** [comment]
Sorry I missed this. Glad that is working for you. Now I'm finished
Codevember I'll spend a bit of time doing some additional documentation
around how things all work in the repo.

**Comment by tcreuro** [comment]
You are too cool for school!
