### ISSUE TITLE
Want to see more drawings!! 

### ISSUE THREAD

**Issue by JestVA** [ajfisher/randomwalks#4]
Hi A what happened lately why no new drawings! Really loved your Instagram and just looking through your repo. 

devfrend

**Comment by ajfisher** [comment]
@JestVA unfortunately a combination of a new role at work + my spare time being taken up by bootstrapping a startup. Definitely a repo I'm going to come back to later this year as both of those things cool off a touch and give me some space back to do more design focussed projects again.

Am also keen to refactor it all to use a more modern JS version and get some of the benefits of Node 12 which I'm working around code wise at various points in the repo as it stands.

**Comment by JestVA** [comment]
Wow, nice one! I know how these things can be demanding. If you need a hand refactoring I would be delighted to help. Like in an OSS project. 
Just let me know what you need by raising an issue and @ing at me. 
Cheers!

**Comment by ajfisher** [comment]
Going to play with this more as part of #codevember this year.
